### ISSUE TITLE
Empty lists

### ISSUE THREAD

**Issue by Etn40ff** [nightflyer73/plugin.video.la7ondemand#2]
Hi nightflyer73,
apparently something changed on the way la7 handles its list of videos: 
http://www.la7.tv/xml/epg/index.xml redirects to their home page now.
As a result your addon does not have any video listed anymore. 
S.

**Comment by nightflyer73** [comment]
It seems this service has been shut down. Even la7 page on cubovision is not updated. This addon will no longer works. Sorry.

**Comment by Etn40ff** [comment]
Thank you anyway
